"""Track if business card for Digicard

Revision ID: 75fa13c13ba6
Revises: 8d0660a728aa
Create Date: 2021-05-15 14:52:15.506241

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "75fa13c13ba6"
down_revision = "8d0660a728aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("is_business_card", sa.Boolean(), nullable=True))
    op.drop_column("orders", "complete")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("orders", "is_business_card")
    # ### end Alembic commands ###
